### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Combustiblemon** [Combustiblemon/Discord-Event-Bot#1]
If you make 2 embeds from different modules at the same time, the bot breaks at the first react with error:
```
console.log('Event: ' + event.name + ', Signup: ' + emoji.name + ', User: ' + username);
                             ^

TypeError: Cannot read property 'name' of undefined
    at messageReactionAdded (C:\Users\Tasos-PC\Desktop\Discord Events bot github\Discord-Event-Bot\commands\PS2OP.js:218:35)
    at Client.<anonymous> (C:\Users\Tasos-PC\Desktop\Discord Events bot github\Discord-Event-Bot\commands\PS2OP.js:200:9)
    at Client.emit (events.js:322:22)
    at MessageReactionAdd.handle (C:\Users\Tasos-PC\Desktop\Discord Events bot github\Discord-Event-Bot\node_modules\discord.js\src\client\actions\MessageReactionAdd.js:44:17)
    at Object.module.exports [as MESSAGE_REACTION_ADD] (C:\Users\Tasos-PC\Desktop\Discord Events bot github\Discord-Event-Bot\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_REACTION_ADD.js:4:37)
    at WebSocketManager.handlePacket (C:\Users\Tasos-PC\Desktop\Discord Events bot github\Discord-Event-Bot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (C:\Users\Tasos-PC\Desktop\Discord Events bot github\Discord-Event-Bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:436:22)
    at WebSocketShard.onMessage (C:\Users\Tasos-PC\Desktop\Discord Events bot github\Discord-Event-Bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:293:10)
    at WebSocket.onMessage (C:\Users\Tasos-PC\Desktop\Discord Events bot github\Discord-Event-Bot\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:310:20)```

**Comment by Combustiblemon** [comment]
Fixed by making one instance of the bot for checking.
